//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_ver3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPM_ver3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add member.
        /// </summary>
        internal static string add_mem_2_pj_fail {
            get {
                return ResourceManager.GetString("add_mem_2_pj_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member successfully.
        /// </summary>
        internal static string add_mem_2_pj_success {
            get {
                return ResourceManager.GetString("add_mem_2_pj_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add project, try again.
        /// </summary>
        internal static string add_pj_fail {
            get {
                return ResourceManager.GetString("add_pj_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is added successfully.
        /// </summary>
        internal static string add_pj_success {
            get {
                return ResourceManager.GetString("add_pj_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your email address below.
        /// </summary>
        internal static string ask_email {
            get {
                return ResourceManager.GetString("ask_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email.
        /// </summary>
        internal static string check_email_4_ac {
            get {
                return ResourceManager.GetString("check_email_4_ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty field is not allowed.
        /// </summary>
        internal static string empty_field {
            get {
                return ResourceManager.GetString("empty_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye1 {
            get {
                object obj = ResourceManager.GetObject("eye1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        internal static string get_password {
            get {
                return ResourceManager.GetString("get_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internet1 {
            get {
                object obj = ResourceManager.GetObject("internet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login_e1645110820608_1024x102411 {
            get {
                object obj = ResourceManager.GetObject("Login-e1645110820608-1024x102411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login_e1645110820608_1024x10242 {
            get {
                object obj = ResourceManager.GetObject("Login-e1645110820608-1024x10242", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to login.
        /// </summary>
        internal static string login_fail_title {
            get {
                return ResourceManager.GetString("login_fail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exist.
        /// </summary>
        internal static string login_notexist {
            get {
                return ResourceManager.GetString("login_notexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SK ^.^.
        /// </summary>
        internal static string login_success {
            get {
                return ResourceManager.GetString("login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        internal static string login_success_title {
            get {
                return ResourceManager.GetString("login_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string title_fail {
            get {
                return ResourceManager.GetString("title_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string title_success {
            get {
                return ResourceManager.GetString("title_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not exist.
        /// </summary>
        internal static string wrong_email {
            get {
                return ResourceManager.GetString("wrong_email", resourceCulture);
            }
        }
    }
}
